### ISSUE TITLE
all killed by aliyun

### ISSUE THREAD

**Issue by passwa11** [BugFor-Pings/PHPwebshell#1]
https://ti.aliyun.com/#/webshell
![image](https://user-images.githubusercontent.com/112363374/234158119-2d88b887-7b73-411d-a9f0-0cc18e1d542e.png)

**Comment by BugFor-Pings** [comment]
杀了不挺正常，自己重新写呗，多简单的。只要放出来就肯定会被杀，这个道理谁都懂
